apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-frontend
  labels:
    app: karsajobs-frontend
    tier: frontend
spec:
  selector:
    matchLabels:
      app: karsajobs-frontend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: karsajobs-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/brondol/karsajobs-ui:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
